version: '3.8'

services:

  # php
  php:
    container_name: php
    build:
      context: .
      target: php
    working_dir: /var/www/laradock
    volumes:
      - ./:/var/www/laradock
    ports:
      - 8000:8000
    depends_on:
      - database
  # DB
  database:
    container_name: database
    image: mysql:8.0
    ports:
      - 3306:3306
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/mysql
volumes:
  db-data: ~