# Use the official MySQL image
FROM mysql:latest

# Set MySQL root password (replace with your desired password)
ENV MYSQL_ROOT_PASSWORD=root

# Create a database and user for Laravel (replace with your database name, user, and password)
ENV MYSQL_DATABASE=laradock_db
ENV MYSQL_USER=root
ENV MYSQL_PASSWORD=
