version: '3'

services:
  php-fpm-container:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - .:/var/www/laradock

  nginx-container:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8000:80"  # Map host port 8000 to container port 80
    depends_on:
      - php-fpm-container

  mysql-container:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    ports:
      - "3306:3306"  # Map host port 3306 to container port 3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laradock_db
      MYSQL_USER: root
      MYSQL_PASSWORD: 

  laradock-container:
    build:
      context: .
      dockerfile: Dockerfile.laravel
      depends_on:
        - php-fpm-container
        - nginx-container
        - mysql-container
